const APP_BAR_TITLE_NAME = "Discover";

const BEST_MOVIE_TILE_NAME = 'BEST POPULAR FILMS AND SERIALS';

const SHOW_CASES_STRING = "SHOW CASES";

const SEE_MORE_SHOW_CASES = "MORE SHOW CASES";

const BEST_ACTOR_TITLE = "ACTORS";

const BEST_MORE_ACTORS = "MORE ACTORS";

const SCREEN_CHECK_MOVIEW_SHOW_TIME = "Check Movie\nShowTimes";

const SEE_MORE_ALL_CAP = "SEE MORE";

const MOVIE_DETAILS_SCREEN_ACTOR = 'ACTORS';

const MOVIE_DETAILS_SCREEN_CREATOR = 'CREATORS';

const MOVIE_DETAILS_SCREEN_SEE_MORE = 'MORE CREATORS';

const MOVIE_DETAILS_STORY_LINE_TITLE = "STORYLINE";
