//Hive Type
const HIVE_TYPE_ID_ACTORVO=1;
const HIVE_TYPE_ID_COLLECTIONVO=2;
const HIVE_TYPE_ID_DATEVO=3;
const HIVE_TYPE_ID_GENRESVO=4;
const HIVE_TYPE_ID_MOVIEVO=5;
const HIVE_TYPE_ID_PRODUCTION_COMPANYVO=6;
const HIVE_TYPE_ID_PRODUCTION_COUNTRYVO=7;
const HIVE_TYPE_ID_SPOKEN_LANGUAGEVO=8;


//Box Name

const BOX_NAME_ACTORVO='BOX_NAME_ACTOR_VO';
const BOX_NAME_COLLECTIONVO='BOX_NAME_COLLECTION_VO';
const BOX_NAME_DATEVO='BOX_NAME_DATE_VO';
const BOX_NAME_GENRESVO='BOX_NAME_GENRES_VO';
const BOX_NAME_MOVIEVO='BOX_NAME_MOVIE_VO';
const BOX_NAME_PRODUCTION_COMPANYVO='BOX_NAME_PRODUCTION_COMPANY_VO';
const BOX_NAME_PRODUCTION_COUNTRYVO='BOX_NAME_PRODUCTION_COUNTRY_VO';
const BOX_NAME_SPOKEN_LANGUAGEVO='BOX_NAME_SPOKEN_LANGUAGE_VO';
